### ISSUE TITLE
Extremely high OSX CPU use

### ISSUE THREAD

**Issue by darthbator** [InfiniteAmmoInc/Yarn#16]
I believe this is related to the following issue

https://github.com/nwjs/nw.js/issues/2723

I believe just integrating the new version should fix it. I should probably do it myself but I am super lazy!

![Issue Image](http://i.imgur.com/wUdEQmr.png)

**Comment by darthbator** [comment]
I went ahead and made a new OSX build from current source based on the newer nwjs library. Issue no longer occurs. You might want to update the packaged build on the website!

https://www.dropbox.com/sh/ffl9b7zg89no8xl/AACijwFJ8X09c9CHyBd0QswCa?dl=0

**Comment by InfiniteAmmoInc** [comment]
Thanks for the head's up!

**Comment by clexit** [comment]
I completely forgot about this issue: Yarn was killing the battery of my laptop. I checked why it was happening, and the culprit is [this line](https://github.com/InfiniteAmmoInc/Yarn/blob/master/app/js/classes/app.js#L111).

Since I have no time for refactoring, I just replaced it with a recursive 1 sec timeout. It solved the issue for me, but I can't make a pull request, because the app doesn't look pretty with this change.

Ideally, the app should:
1. Use `requestAnimationFrame` instead of `setInterval`
2. Cache all calculations (especially DOM-related ones) and recalculate stuff only when it's required (meaning, something's changed). I don't remember the details, but the `updateArrows` function is doing a lot of calculations and DOM queries that are CPU-consuming.

I'd recommend not to look at the Energy tab in Activity monitor before this refactoring happens :)

**Comment by darthbator** [comment]
Do you happen to have that change stashed in a branch somewhere? I'd like to check that out and build it so this works on my laptop during some travel I have coming up over the next few months.

**Comment by clexit** [comment]
It's probably too late for that now, but maybe you can still use it :)

The changes are in [master](https://github.com/clexit/Yarn). You can play with it [here](https://cdn.rawgit.com/clexit/Yarn/f75d23aa/app/index.html).

I'm not sure about a PR, since this version adds a slight delay for arrows, so they don't look as pretty as in the current Yarn version. On the other hand, the current version uses a lot of CPU event when you're not working with it, and the updated one uses 0%:

![bildschirmfoto 2017-01-19 um 13 29 29](https://cloud.githubusercontent.com/assets/1017495/22107048/2974b530-de4c-11e6-80ed-e8b168dcd491.png)

**Comment by Subliminalman** [comment]
Is this change going to be be pulled in? My fans blaze after a few minutes with Yarn open.

**Comment by desplesda** [comment]
I played with the live demo that @clexit put up (thanks for doing that! Makes testing super handy :) ) - it feels pretty OK to me. Making sure that arrows always immediately redraw when you zoom is a very nice touch.

@clexit, would you like me to merge this in? (You didn't explicitly state that you wanted to, just that you were unsure if a PR was appropriate, so I'm double-checking to be sure.)

**Comment by clexit** [comment]
Yeah, I wasn't sure if you prefer super smooth arrows or less CPU consumption. I opened https://github.com/InfiniteAmmoInc/Yarn/pull/50

**Comment by darthbator** [comment]
Is this planning to be pulled in? I'm sort of just pining this issue to remind everyone about it :)

**Comment by desplesda** [comment]
Merged #50! Thanks for the reminder.

**Comment by Subliminalman** [comment]
Thanks for getting that in! Worked on stuff last night and my lap didn't catch fire 😄
