### ISSUE TITLE
osx associate yarn with file types

### ISSUE THREAD

**Issue by HawkenKing** [InfiniteAmmoInc/Yarn#33]
would be nice to associate yarn with file types so it opens when double clicking a Json etc.

**Comment by desplesda** [comment]
This one's unfortunately more tricky than it sounds. 

The file extension needs to be .json because Unity will only treat files as plain text if they end in .json, .txt or .xml. This means that we can't define a custom ".yarn" extension. 

However, Yarn shouldn't claim the .json file extension because not all .json files are going to be Yarn files. 

(I wonder if we could define a file extension like ".yarn.json".)

**Comment by HawkenKing** [comment]
Letter Yarn claim Json is fine, Adobe do it all the time! :)
It doesn't come up on the list of software that supports .json when inspecting a .json file. If it could appear in there that would be nice.
