### ISSUE TITLE
Expand Shortcut Nodes?

### ISSUE THREAD

**Issue by zonk-ossian** [InfiniteAmmoInc/Yarn#99]
My yarn interpreter has problems with the Shortcut style syntax so I need to expand each shortcut into its own node. Any ideas?

**Comment by blurymind** [comment]
this is a known issue with bondage.js, which is what we use to parse the data when previewing it in yarn. 
What game engine are you using? If it's unity, then your bug is for https://github.com/thesecretlab/YarnSpinner
If you mean the previewer in yarn editor, then your report is for bondage.js and i already raised an issue here https://github.com/jhayley/bondage.js/issues/31
